from pathlib import Path
import json,hashlib,shutil
P=Path('/media/mizuki/HD Externo II/Claude/Claude 2/sistema/05-material/livro/planejamento-editorial');M=P/'consolidacao/lote-01/migracao-nomes';C=M/'remissoes';sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
notes={'regras-gerais/lote-final':{14:'Remissão final Dano e recuperação em negrito; a linha permanece acima do rodapé sem sobreposição.'},'equipamento/lote-final':{1:'Remissão Ataques cabe na abertura e não desloca os quadros.',4:'Remissão condensada em duas linhas. Eliminada página órfã; quadro inteiro, exemplo e fechamento cabem na mesma página.',9:'Exemplo serve à proteção disponível na ficha; caixa completa, sem quebra.',13:'Referências em negrito distinguem os títulos compostos; todas as seções continuam completas.',26:'Remissão Ataques no último parágrafo mantém espaço e leitura regulares.'},'origens/lote-01':{17:'Remissão Vida a zero no parágrafo de cura; tabela e exemplo permanecem íntegros.'},'caminhos/bastiao/lote-01':{3:'Socorro localizado no parágrafo de Ainda de Pé; títulos e demais habilidades preservados.',4:'Vida a zero na última observação da transferência; exemplos íntegros.',10:'Referência à reserva temporária no encerramento; quadro e regra de Embalo completos.'}}
for r in json.loads((C/'QA-PIXELS.json').read_text()):
 n=r['unidade'];b=P/n;e=b/'evidencias';config=json.loads((b/'VALIDACAO.json').read_text());source=b/config['manuscrito'];pdf=b/'output/pdf'/config['pdf'];assert sha(pdf)==r['sha256_depois'];old=json.loads((C/'qa-antes'/n/'evidencias/inspecao-visual.json').read_text());rows=[]
 for x in r['registros']:
  i=x['pagina'];row=dict(old['paginas'][i-1]);row.update(sha256_png=x['sha256_depois'],pixels_iguais_rodada_anterior=x['igual'])
  if x['igual']:row['evidencia_preservacao']='Pixel idêntico à prova imediatamente anterior já examinada; sem nova abertura nesta rodada.'
  else:row.update(resultado='sem defeito visual observado',observacoes=notes[n][i],revisor='/root/compatibilidade',inspecao_realizada='PNG aberto individualmente após correção de remissões.')
  dest=b/'output/png'/f'pagina-{i:02}.png';dest.parent.mkdir(parents=True,exist_ok=True);shutil.copy2(x['imagem'],dest);row['imagem']=str(dest.relative_to(b));rows.append(row)
 inspection={'data':'2026-10-03','sha256_texto':sha(source),'sha256_pdf':sha(pdf),'metodo':'Abertura de cada página modificada pelas remissões; conservação da avaliação anterior por igualdade de pixels nas outras páginas.','comparacao':'evidencias/COMPARACAO-REMISSOES-PDF.json','prova_anterior':r['sha256_antes'],'paginas':rows,'limites':'Sem impressão física, playtest ou teste com leitores humanos.'};(e/'inspecao-visual.json').write_text(json.dumps(inspection,ensure_ascii=False,indent=2)+'\n')
 delta={'sha256_texto':sha(source),'sha256_pdf':sha(pdf),'alteracoes':str((C/'ALTERACOES.json').relative_to(P)),'revisao_independente':'/root aprovou as remissões propostas e seus antes/depois em REMISSOES-TEXTUAIS.md; leitura contextual e execução por /root/compatibilidade.','regra':'Nenhum dado, custo, ação, gatilho ou requisito alterado. Uniforme refere a proteção disponível na ficha sem presumir energia.','visual_paginas_abertas':r['alteradas'],'visual_identicas':config['paginas']-len(r['alteradas'])};(e/'REVISAO-REMISSOES.json').write_text(json.dumps(delta,ensure_ascii=False,indent=2)+'\n')
 v=json.loads((b/'VALIDADORES.json').read_text());v.update(sha256_texto=sha(source),sha256_pdf=sha(pdf));v['revalidacao_remissoes']=delta
 for item in v['validadores']:item['delta_remissoes']='evidencias/REVISAO-REMISSOES.json'
 (b/'VALIDADORES.json').write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n')
# Record root's explicit independent confirmation of both nominal complements.
for n in ['aptidoes/lote-01','origens/lote-01']:
 b=P/n;e=b/'evidencias';q=e/'REVISAO-NOMES.json';j=json.loads(q.read_text());j['revisao_independente_delta']['complemento']='Confirmado pelo revisor /root após leitura integral de COMPLEMENTO.json: sem alteração numérica ou funcional.';q.write_text(json.dumps(j,ensure_ascii=False,indent=2)+'\n');q=b/'VALIDADORES.json';j=json.loads(q.read_text());j['revalidacao_nomes']['revisao_independente_delta']['complemento']='Aprovado por /root após leitura de COMPLEMENTO.json.';q.write_text(json.dumps(j,ensure_ascii=False,indent=2)+'\n')
