from pathlib import Path
import json,hashlib,shutil
P=Path('/media/mizuki/HD Externo II/Claude/Claude 2/sistema/05-material/livro/planejamento-editorial');M=P/'consolidacao/lote-01/migracao-nomes';sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();units=json.loads((M/'QA-UNIDADES.json').read_text());out=[]
np={x['unidade']:x for x in json.loads((M/'QA-PIXELS.json').read_text())};rp={x['unidade']:x for x in json.loads((M/'remissoes/QA-PIXELS.json').read_text())}
for n in units:
 b=P/n;c=json.loads((b/'VALIDACAO.json').read_text());source=b/c['manuscrito'];pdf=b/'output/pdf'/c['pdf'];check=json.loads((b/'CONFERENCIA.json').read_text());assert check['ok'] and check['sha256_texto']==sha(source) and check['sha256_pdf']==sha(pdf);v=json.loads((b/'VALIDADORES.json').read_text());assert v['sha256_texto']==sha(source);v['fechamento_migracao']={'estado':'concluído no escopo nominal e remissões','conferencia':'CONFERENCIA.json','limites':'Evidências mecânicas anteriores preservadas e execuções repetidas nos textos atuais. Revisão de nomes/remissões não é novo playtest.','paginas_abertas':sorted(set(np[n]['alteradas']+rp.get(n,{}).get('alteradas',[])))};(b/'VALIDADORES.json').write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n')
 files=[{'arquivo':str(f.relative_to(b)),'sha256':sha(f),'bytes':f.stat().st_size} for f in sorted(b.rglob('*')) if f.is_file() and f.name!='MANIFESTO.json' and '__pycache__' not in f.parts]
 manifest={'data':'2026-10-03','status':'candidata revisada e congelada para consolidação; não publicada','manuscrito':c['manuscrito'],'sha256_texto':sha(source),'sha256_pdf':sha(pdf),'paginas':c['paginas'],'arquivos':files};(b/'MANIFESTO.json').write_text(json.dumps(manifest,ensure_ascii=False,indent=2)+'\n')
 out.append({'unidade':n,'sha256_texto':sha(source),'sha256_pdf':sha(pdf),'paginas':c['paginas'],'paginas_alteradas_abertas':v['fechamento_migracao']['paginas_abertas'],'conferencia_ok':True,'checks':check['verificacoes'],'manifesto_sha256':sha(b/'MANIFESTO.json')})
(M/'QA-FECHAMENTO.json').write_text(json.dumps(out,ensure_ascii=False,indent=2)+'\n')
(M/'QA-FECHAMENTO.md').write_text('# Fechamento das oito unidades\n\nFontes congeladas. Conferência final: '+str(sum(x['checks'] for x in out))+' verificações passaram, '+str(sum(x['paginas'] for x in out))+' páginas. As 30 páginas alteradas foram abertas individualmente; 167 conservam a avaliação anterior por identidade de pixels ou do PDF inteiro.\n\nRenomes têm revisão independente da raiz; o complemento de Aptidões/Origens também foi lido integralmente pela raiz. Remissões foram identificadas por rotas_didatica e aprovadas pela raiz antes da aplicação. Resultados documentais e modelos não são playtest ou teste com leitores humanos.\n\n| Unidade | Texto SHA | PDF SHA | Checks |\n|---|---|---|---|\n'+''.join(f"| {x['unidade']} | {x['sha256_texto'][:12]} | {x['sha256_pdf'][:12]} | {x['checks']} |\n" for x in out))
folder=M/'execucao-preservada';folder.mkdir(exist_ok=True)
for name in ['complemento-qa-nomes.py','atualizar-donos-nomes.py','render-qa-nomes.py','render-complemento-nomes.py','fechar-qa-nomes.py','aplicar-remissoes-compat.py','render-remissoes.py','fechar-remissoes-compat.py','manifestos-finais-compat.py']:
 shutil.copy2(Path('/tmp')/name,folder/name)
print(json.dumps(out,ensure_ascii=False,indent=2))
