from pathlib import Path
import json
P=Path('/media/mizuki/HD Externo II/Claude/Claude 2/sistema/05-material/livro/planejamento-editorial');paths=json.loads((P/'consolidacao/lote-01/ORDEM.json').read_text())['fontes']
patches={
'origens': [('quando você ficaria **Guarda Aberta**','quando você ficaria **com a Guarda Aberta**')],
'equip':[('Estar apenas Agarrado, Derrubado, Atordoado ou Guarda Aberta não basta.','Estar apenas Agarrado, Derrubado, Atordoado ou com a Guarda Aberta não basta.')],
'progressao':[('três Talentos concedidos, separadas das compras','três Talentos concedidos, separados das compras'),('uma vaga própria para ela além do limite','uma vaga própria para ele além do limite')],
'fundamento':[('Suas Categorias de Efeito 1, 2 e 3','Suas **Categorias de Efeito (CE)** 1, 2 e 3'),('A Livre não ocupa espaço; Regra Própria segue o custo específico de sua progressão. Nenhuma delas permite comprar efeitos de uma Família Fechada por outro nome.','A Expressão da técnica não ocupa espaço; Regra Própria segue o custo específico de sua progressão. Nenhuma dessas opções permite comprar efeitos de uma Família Fechada por outro nome.')],
'catalogo': [('As [Talentos]','Os [Talentos]'),('Algumas atuam por um gatilho. Outras exigem ação, Reação ou PE.','Alguns atuam por um gatilho. Outros exigem ação, Reação ou PE.'),('um Talento específica','um Talento específico'),('Talentos da mesma Classe','Talentos da mesma Categoria'),('Custos e níveis da Classe escolhida','Custos e níveis da Categoria escolhida'),('Talento da mesma Classe','Talento da mesma Categoria'),('nem toda Talento','nem todo Talento'),('A Expressão da técnica permanece uma opção de aparência e expressão da técnica.','A Expressão da técnica reúne detalhes de aparência e expressão pessoal.'),('Retirar os números da descrição não transforma esse benefício em Livre.','Retirar os números da descrição não transforma esse benefício numa Expressão da técnica.')],
'aptidoes':[('com os Talentos da mesma Classe. Efeitos pequenos ou de informação costumam caber na Classe 1. Intervenções mais relevantes podem exigir Classe 2 e seu limite por cena. Permanência, sozinha, não transforma um benefício pequeno em Classe 3. Efeitos que precisem dessa terceira Classe ficam fora desta opção.','com os Talentos da mesma Categoria de Efeito. Efeitos pequenos ou de informação costumam caber na Categoria 1. Intervenções mais relevantes podem exigir Categoria 2 e seu limite por cena. Permanência, sozinha, não transforma um benefício pequeno em Categoria 3. Efeitos que precisem dessa terceira Categoria ficam fora desta opção.')],
'rotas':[('Classe 2 ocupa dois espaços e exige nível 7. Classe 3 ocupa três espaços e exige nível 13. Elas contam no máximo de cinco Talentos pagos.','Categoria 2 ocupa dois espaços e exige nível 7. Categoria 3 ocupa três espaços e exige nível 13. Eles contam no máximo de cinco Talentos pagos.'),('Talento Leitura**, do Catálogo de criação: ela identifica','Talento Leitura**, do Catálogo de criação: ele identifica'),('Cada uma tem seu próprio gatilho e frequência. Pague seus espaços de Kata e confira o nível exigido antes de registrá-la.','Cada um tem seu próprio gatilho e frequência. Pague seus espaços de Kata e confira o nível exigido antes de registrá-lo.'),('Um Talento criada','Um Talento criado'),('O Talento Raiz pode ocupar um dos outros espaços de Rika, respeitando sua compra normal. Ela não vem junto da semente.','O Talento Raiz pode ocupar um dos outros espaços de Rika, respeitando sua compra normal. Ele não vem junto da semente.'),('O Talento Recomposição pode fazer parte do estilo quando Caio atingir **nível 7** e pagar seus **dois espaços**. Ela não está disponível','O Talento Recomposição pode fazer parte do estilo quando Caio atingir **nível 7** e pagar seus **dois espaços**. Ele não está disponível'),('O Talento é concedida','O Talento é concedido'),('além do máximo de cinco pagas','além do máximo de cinco pagos'),('Um Talento ou Bênção criada na mesa não permite receber uma entrada indisponível sob outro nome.','Criar um Talento ou uma Bênção na mesa não permite receber uma entrada indisponível sob outro nome.'),('limitar a proposta à Classe 1 ou 2','limitar a proposta à Categoria de Efeito 1 ou 2')],
'campo':[('Um talento que **não possa ser desligada**','Um talento que **não possa ser desligado**'),('se o talento pode ser desligada','se o talento pode ser desligado')],
'construcao':[('numa talento','num talento'),('Talentos são características da ficha. Algumas funcionam continuamente. Outras possuem gatilhos, ações ou custos. A entidade ganha **uma no nível 1** e outra nos níveis','Talentos são características da ficha. Alguns funcionam continuamente. Outros possuem gatilhos, ações ou custos. A entidade ganha **um no nível 1** e outro nos níveis'),('A Classe indicada identifica a categoria da opção.','A CE indicada identifica a Categoria de Efeito da opção.'),('Essas quatro talentos','Esses quatro talentos'),('Use **Talento Próprio** para uma capacidade que a lista não representa. Ela ocupa uma das escolhas recebidas pela entidade.','Use **Talento Próprio** para uma capacidade que a lista não representa. O Talento ocupa uma das escolhas recebidas pela entidade.')],
'evocador':[('Toda talento concedido','Todo talento concedido')]
}
for key,items in patches.items():
 p=P/paths[key];s=p.read_text()
 for old,new in items:
  assert s.count(old)==1,(key,old,s.count(old));s=s.replace(old,new)
 p.write_text(s)
print('Ajustes contextuais aplicados:',sum(len(v) for v in patches.values()))
